### ISSUE TITLE
No 'Make CON Votes' Button

### ISSUE THREAD

**Issue by Mongkii** [thomas-ashcraft/alienware_arena_helper#1]
The 'Make CON Votes' just disappeared today, while TOT button works well.
Could you please fix it?
Thanks a lot!

**Comment by AleksandrSolovchuk** [comment]
I have it since yesterday

**Comment by thomas-ashcraft** [comment]
Fixed in https://github.com/thomas-ashcraft/alienware_arena_helper/commit/1ce3247cab9f612bf76c54e0012c5d8e31d0e7f0
