### ISSUE TITLE
New Site Interface

### ISSUE THREAD

**Issue by Kureka** [thomas-ashcraft/alienware_arena_helper#12]
Please fix auto vote feature for new site interface.

**Comment by mahadi22** [comment]
yup, new interface and new system, but voting system still using old link,
https://www.alienwarearena.com/ucf/vote/(up or down)/(threadnumber)

anyone can confirm voting still giving arp ? its 1 arp per 5vote in old site for daily vote on content

**Comment by thomas-ashcraft** [comment]
Already checking new AWA interface and features.

For now I don't see that voting is still counts as daily activity. Correct me if I'm wrong.

As for the other script features that still lacks in new interface - I will definitely update them.

**Comment by mahadi22** [comment]
> Already checking new AWA interface and features.
> For now I don't see that voting is still counts as daily activity. Correct me if I'm wrong.
> As for the other script features that still lacks in new interface - I will definitely update them.

thakn you for the reply ❤️
after voting up/down on many thread, its still give arp, its seems stil using old system, 1 arp for 5 vote, but it didnt have pointer or stat how many i already vote on that day

**Comment by thomas-ashcraft** [comment]
> after voting up/down on many thread, its still give arp, its seems stil using old system, 1 arp for 5 vote, but it didnt have pointer or stat how many i already vote on that day

Thank you for information! It really helps since I don't have a lot of free time right now, to fully investigate all of this.

If old backend arp system still here it means we could use some of it hidden features to bring arp info back. The old interface has some unused backend for updating pager (hovering thing in corner with arp info). Will try to find old notes with links to that backend.

Also need to figure out where to place the script interface and voting buttons.

**Comment by thomas-ashcraft** [comment]
The old address that could be used to read the ARP status is now useless.
https://eu.alienwarearena.com/esi/USER_SPECIFIC/arpStatusToast

So far I can’t find a way to check any daily ARP information, except for the user's lifetime total points.

**Comment by profesy** [comment]
I can not understand how to use in connection with the new interface, do not tell me how ?
Opera 63.0.3368.53 not working

**Comment by thomas-ashcraft** [comment]
> I can not understand how to use in connection with the new interface, do not tell me how ?
1. Make sure you are logged in.
2. Go to News or Videos section.
3. Click on of the new buttons you see at top bar. (Those up and down arrows in cubes)

![image_2019-08-31_00-48-02](https://user-images.githubusercontent.com/6583664/64052955-108aca00-cb89-11e9-89ff-6d08d57e46b2.png)

**Comment by Rudokhvist** [comment]
Hi, I found a way to get daily ARP information
https://www.alienwarearena.com/api/v1/users/arp/status

**Comment by thomas-ashcraft** [comment]
All suggestions from this topic have been implemented. Issue resolved and will be closed.
Feel free to create new issues/suggestions/discussions!

Special thanks to @Ryzhehvost for discovering vital API link!

**Comment by profesy** [comment]
https://radikal.ru/lfp/a.radikal.ru/a25/2008/92/a856231b9a65.png/htm

does not work
how can I fix the problem
