### ISSUE TITLE
Скрипт перестал работать на Greasemonkey 4.0+

### ISSUE THREAD

**Issue by nlboom** [thomas-ashcraft/alienware_arena_helper#2]
С переходом на Firefox Quantum скрипт перестал работать. Окошко в нижнем правом углу появляется, но кнопки для получения балов за голосования нет. Использую Firefox 59.0.1 и Greasemonkey 4.3.

**Comment by thomas-ashcraft** [comment]
Коротко:
Я отказался от поддержки Greasemonkey, начиная с его версии 4.0. Используйте вместо него Tampermonkey.
https://addons.mozilla.org/ru/firefox/addon/tampermonkey/
Если вы делали какие-то настройки в опциях скрипта, то они останутся после переустановки через другой аддон.

Развёрнуто:
Дело в том, что авторы Greasemonkey, начиная с версии 4.0, в погоне за асинхронностью, изменили область видимости запускаемых скриптов (scope) непонятным образом, не составив подробной документации. И теперь нельзя скриптом, запущенным Гризманки, просто взять и добраться до функций и переменных определённых скриптами, запущенными страницей. А из этого добра наш скрипт использует jQuery, загруженный самим сайтом (ибо я верю что не стоит загружать лишние копии фреймворка ради маленького скрипта). И конечно же наш скрипт использует переменные сайта. Например, информация по полученным пользователем ключам (используется в подсветке/затенении взятых раздач на странице с их списком).

Если кто-то желает помочь в этом вопросе, то делайте pull request - я буду очень рад!

**Comment by nlboom** [comment]
Поставил Tampermonkey, в нём скрипт также не работает. Симптомы те же. Использую Tampermonkey 4.6.5757 и Firefox Quantum 59.0.2.

**Comment by thomas-ashcraft** [comment]
Не так давно Alienware Arena переделали систему голосования. И теперь голосовать за комментарии невозможно. Можно голосовать только за контент (форумные темы, изображения, видео, новости). Для этого был написан новый алгоритм и кнопки для автоматического голосования перенесены в левую колонку сайта.

В связи с этим всем вопрос: а вы точно ищете кнопки там, где они теперь должны быть?
<details>
<summary>Пара скриншотов с новым расположением кнопок: (кликните чтобы раскукожить) (click to expand)</summary>

![Alienware Arena helper screenshot Featured images](https://user-images.githubusercontent.com/6583664/38822279-a8a99000-41ab-11e8-8708-85d73328049c.png)

![Alienware Arena helper screenshot member's page](https://user-images.githubusercontent.com/6583664/38822298-b0223cc4-41ab-11e8-8ebc-c658d25124c4.png)
</details>

**Comment by nlboom** [comment]
Всё нормально, ложная тревога. Я просто не заметил новых кнопок.
