### ISSUE TITLE
Verifying post date doesn't work anymore

### ISSUE THREAD

**Issue by Lucki** [thomas-ashcraft/alienware_arena_helper#24]
Following post time search doesn't work anymore:
https://github.com/thomas-ashcraft/alienware_arena_helper/blob/b4fe86e41b54676f1c108f93a5a7704e02c09688/alienwarearena_helper.user.js#L880

The relevant part is missing and probably hidden inside some obscure javascript: 
~~~
<span class="timeago"></span>
~~~

**Comment by thomas-ashcraft** [comment]
Just looked into this. Don't know what they thinking. It almost looked like they've finally started to trying to not duplicate data, sent over net.

All the timestamps for that particular ```<span>``` you targeting is now taken from ```<article>``` by ```updatePostTimes()``` function. But thats function affects only comments, not first message of topic. Looks like the first message is considered a content. Like in other sections: news, videos, images, etc... Anyway.

Timestamp for the first message is inside anonymous JS function, inside yet another ```<script>``` tag. Just like that:
```JS
$('.common__op-meta .profile-username .timeago').attr('title', '2019-11-02 04:06:58Z').timeago();
```

RegEx like this one should do the job
```RegExp
/\$\('\.common__op-meta .*?\.timeago'\)\.attr\('title', '(.*?)'\)\.timeago\(\);/
```

**Comment by thomas-ashcraft** [comment]
Closed in https://github.com/thomas-ashcraft/alienware_arena_helper/commit/e4f5b926745a1907b706dec64ba361a733f282a3

**Comment by thomas-ashcraft** [comment]
Why the hell only after a commit I remembered that status object (the one we getting from API) have current quest's start and end timestamps? Means I shouldn't made those date calculations.
