### ISSUE TITLE
Does not work with new ARP version

### ISSUE THREAD

**Issue by d355** [thomas-ashcraft/alienware_arena_helper#4]

**Comment by thomas-ashcraft** [comment]
I'm aware of the problem. Development of the new version is in process (as you can see in [dev](/thomas-ashcraft/alienware_arena_helper/tree/dev) branch). I'm trying to release proper new version ASAP.

**Comment by thomas-ashcraft** [comment]
Fixed in https://github.com/thomas-ashcraft/alienware_arena_helper/commit/e28aa3c084c9afcd08ecf35f94b4d2a0f1dbd561
