### ISSUE TITLE
Не работает последняя версия :(

### ISSUE THREAD

**Issue by elfl0rd** [thomas-ashcraft/alienware_arena_helper#8]
Не голосует и даже панель настроек не открывается...

**Comment by thomas-ashcraft** [comment]
Спасибо за сообщение!
Отображение статуса и панели настроек, исправлено сегодня в версии 0.5.8 (https://github.com/thomas-ashcraft/alienware_arena_helper/commit/60d338c59bc9008010ad168bab5bb978b522f2de). Это произошло потому, что на сайте Alienware Arena слегка изменили критически важный фрагмент CSS кода. К слову, голосование работало, просто внешне процесс не отображался.

**Comment by elfl0rd** [comment]
Спасибо!
